version: "2"
services:
  letreca_api:
    container_name: letreca_api
    build: . 
    ports:
      - "3001:3000"
    depends_on:
      - letreca_db
    links:
      - letreca_db
      
  letreca_db:
    container_name: letreca_db
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=letreca_db